// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

export const isConfigured = !!(
  SUPABASE_URL &&
  SUPABASE_PUBLISHABLE_KEY &&
  SUPABASE_URL !== 'your_project_id_here' &&
  !SUPABASE_URL.includes('your_project_id') &&
  SUPABASE_PUBLISHABLE_KEY !== 'your_publishable_key_here'
);

// Create a chainable mock query builder that prevents runtime crashes for db query calls
const mockQueryBuilder: any = {
  select: () => mockQueryBuilder,
  eq: () => mockQueryBuilder,
  order: () => mockQueryBuilder,
  limit: () => mockQueryBuilder,
  single: () => mockQueryBuilder,
  insert: () => mockQueryBuilder,
  update: () => mockQueryBuilder,
  delete: () => mockQueryBuilder,
  then: (resolve: any) => resolve({ data: [], error: null }),
};

export const supabase = isConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : new Proxy({} as any, {
      get(target, prop) {
        if (prop === 'auth') {
          return {
            onAuthStateChange: () => ({
              data: { subscription: { unsubscribe: () => {} } },
            }),
            getSession: async () => ({ data: { session: null } }),
          };
        }
        if (prop === 'from') {
          return () => mockQueryBuilder;
        }
        if (prop === 'rpc') {
          return () => Promise.resolve({ data: null, error: null });
        }
        return () => Promise.resolve({ data: null, error: null });
      }
    });